cloud:
  aws:
    credentials:
      access-key: AKIAQGTIKVX6365OUIGU
      secret-key: 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

    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: school-managment-uploads


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB